### ISSUE TITLE
[Reaserch] GitHub CI/CD - Expo/react-native

### ISSUE THREAD

**Issue by bartlomiejmont** [KuzniaCo/chemistry-app#6]
Adding CI/CD to our project will boost team's productivity. You will need to find out to if there is an easy way to create continues integration pipeline using github actions.

**Comment by hubcio2115** [comment]
We can introduce testing with [React Native Testing Library](https://callstack.github.io/react-native-testing-library/) and make actions that will check if it runs all the test.

It will require from us that we will learn how to make tests and actually write them. But some of the pros are:
 - It will make checking if something actually works easy
 - Our changes didn't break something somewhere else in the app

Also since we are using typescript at this moment we can get the action that checks if our app builds with no errors. Introduction of Eslint would be also nice.

**Comment by bartlomiejmont** [comment]
@hubcio2115 Also we should check if code meets our lint/prettier rules. 

[React Native Testing Library](https://callstack.github.io/react-native-testing-library/) sounds fine but the question is also with integration with github actions. Can you find out if it is worth our effort ?

**Comment by hubcio2115** [comment]
In case of checking the rules, yeah that'd be nice.

In case of this actions, I found an article about testing React apps with Jest, and there is a part of the article talking about GitHub Actions and how to set an action for running the tests.
